# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='distance_pref',
            field=models.CharField(choices=[('km', 'kilometers'), ('mi', 'miles')], default='mi', max_length=2),
        ),
    ]
