# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-05 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_userprofile_distance_pref'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hide_real_name',
            field=models.BooleanField(default=False, help_text='If checked, username will be shown in place of First/Last'),
        ),
    ]
