# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0011_auto_20160607_0707'),
        ('people', '0003_userprofile_hide_real_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookmarks',
            field=models.ManyToManyField(to='trails.Trail'),
        ),
    ]
