# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_userprofile_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_contact',
            field=models.BooleanField(default=True, help_text='Allow other site members to contact me with questions about trails.'),
        ),
    ]
