# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_optional_bookmarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='trails.Trail'),
        ),
    ]
