# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_auto_20160518_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='public',
            field=models.BooleanField(default=True, help_text='Visible to the world'),
        ),
    ]
