# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0003_trail_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='trail_type',
            field=models.CharField(choices=[('loop', 'Loop'), ('tb', 'There and Back'), ('ow', 'One Way')], default='loop', max_length=6),
        ),
    ]
