# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0004_trail_trail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='featured',
            field=models.BooleanField(default=False, help_text='Editor picks'),
        ),
    ]
