# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_trail_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='urlhash',
            field=models.CharField(default='', max_length=6),
        ),
    ]
