# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0006_trail_urlhash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='urlhash',
            field=models.CharField(max_length=6),
        ),
    ]
