# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_auto_20160520_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='urlhash',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
