# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0008_auto_20160521_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='region',
            field=models.CharField(default='Yosemite', help_text='e.g. Yosemite, CA', max_length=120),
            preserve_default=False,
        ),
    ]
