# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0010_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='trail',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
