# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0011_auto_20160607_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='activity_type',
            field=models.CharField(choices=[('hike', 'Hike/Walk'), ('bike', 'Bike')], default='hike', max_length=6),
        ),
        migrations.AddField(
            model_name='trail',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('mod', 'Moderate'), ('hard', 'Strenuous')], default='mod', max_length=6),
        ),
        migrations.AddField(
            model_name='trail',
            name='season',
            field=models.CharField(choices=[('all', 'Year-Round'), ('mild', 'Spring Through Fall')], default='all', max_length=6),
        ),
        migrations.AlterField(
            model_name='trail',
            name='region',
            field=models.CharField(help_text="e.g. 'Yosemite' or 'New York'", max_length=120),
        ),
    ]
