# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0012_auto_20160804_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='directions',
            field=models.TextField(blank=True, null=True, verbose_name='Driving or Trail Directions'),
        ),
    ]
