# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0013_trail_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trail',
            name='distance',
            field=models.PositiveIntegerField(blank=True, help_text='Stored as meters', null=True),
        ),
    ]
