# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0014_auto_20160805_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='urlhash',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, unique=True),
        ),
    ]
